server:
  port: 3000
  env: development
  apikey: "7mhmLJzo3vaYOHqiRLGzhizuH9gSDk-y3MzwzLnSA8uNuUkf8dw6zNwH1i8Qp"

database:
  host: localhost
  port: 5432
  user: postgres
  password: "postgres"
  database: daily_alu_local
  name: daily_alu_local
  sslmode: disable

jwt:
  secret: "nfN1BQSSRGkzZmX7KnjGHrwmGqrm8w-jaVHGIqBIv3nN3TTFOQdG3CUur4cYd"
  refresh-secret-key: "NmlA5LxMoEaPpCewzJhDLBGMvwCEaD"
  expiry: 24 # hours
  refresh-expiry: 120 # hours


redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

aws:
  region: ap-southeast-1
  s3:
    bucket: dailyalu-storage
  ses:
    sender: no-reply@dailyalu.com

logging:
  level: debug
  format: json

ratelimit:
  enabled: true
  default:
    max: 60         # Default: 60 requests
    expiration: 60  # Default: 60 seconds window
  
  # Endpoint-specific rate limits
  endpoints:
    # User endpoints
    post.api_v1_auth_login:
      max: 4
      expiration: 60
    post.api_v1_auth_register:
      max: 5
      expiration: 60
    get.api_v1_users:
      max: 5
      expiration: 60
    post.api_v1_users:
      max: 5
      expiration: 60
      