# This workflow will build and test a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Daily Alu Server CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Install Dependencies
      run: go get .

    - name: Build
      run: go build -v -o dailyalu-server ./main.go

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dailyalu-server
        path: dailyalu-server

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Install Dependencies
      run: go get .

    - name: Run Tests
      run: |
        go test -v -json dailyalu-server/internal/utils > test-results.json

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.json
